/** @format */

export const TEST_IDS = {
  LOGIN: {
    LANGUAGE_BUTTON: 'LOGIN_LANGUAGE_BUTTON',
    SIGN_IN_BUTTON: 'LOGIN_SIGN_IN_BUTTON',
    FORGOT_BUTTON: 'LOGIN_FORGOT_BUTTON',
    EMAIL_INPUT: 'LOGIN_EMAIL_INPUT',
    PASSWORD_INPUT: 'LOGIN_PASSWORD_INPUT',
    SHOW_PASSWORD_BUTTON: 'LOGIN_SHOW_PASSWORD_BUTTON',
  },
  FORGOT_PASSWORD: {
    SEND_BUTTON: 'FORGOT_PASSWORD_SEND_BUTTON_BUTTON',
    BACK_BUTTON: 'FORGOT_PASSWORD_BACK_BUTTON',
    EMAIL_INPUT: 'FORGOT_PASSWORD_LOGIN_EMAIL_INPUT',
  },
};
